apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-22.04
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://cloud-images.ubuntu.com/minimal/releases/jammy/release-20220901/ubuntu-22.04-minimal-cloudimg-amd64.img"
spec:
  storageClassName: hpe-standard01
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
