---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dv-rocky9-int-test
spec:
  dataSource:
    name: dv-rocky9-int
    kind: PersistentVolumeClaim
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
