apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  name: kubevirt
  namespace: kubevirt
spec:
  imagePullPolicy: IfNotPresent
  infra:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          operator: Exists
  workloads:
    nodePlacement:
      nodeSelector:
        node.ike.iij.jp/virtualization: "true"
      tolerations:
        - effect: NoSchedule
          operator: Exists
  configuration:
    developerConfiguration:
      featureGates:
        - AutoResourceLimitsGate
        - ExperimentalVirtiofsSupport
      logVerbosity:
        virtLauncher: 2
        virtHandler: 3
        virtController: 4
        virtAPI: 2
        virtOperator: 6
