apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-console-vnc-port-forward-access
rules:
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/console
      - virtualmachineinstances/vnc
    verbs:
      - get
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachineinstances/portforward
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt
  namespace: keisuk-t
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-console-vnc-port-forward-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: keisuk-t
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: users:keisuk-t
