---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-2204-ike
spec:
  storageClassName: hpe-standard01
  dataSource:
    name: ubuntu-22.04
    kind: PersistentVolumeClaim
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
