apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: vmpool-test
spec:
  replicas: 30
  selector:
    matchLabels:
      kubevirt.io/vmpool: vmpool-test
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: vmpool-test
    spec:
      runStrategy: Always
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: vmpool-test
        spec:
          domain:
            devices:
              disks:
              - disk:
                  bus: virtio
                name: containerdisk
            resources:
              requests:
                memory: 512Mi
          terminationGracePeriodSeconds: 0
          volumes:
          - containerDisk:
              image: ikr.iij.jp/virt/rocky:9
            name: containerdisk
          - cloudInitNoCloud:
              userDataBase64: I2Nsb3VkLWNvbmZpZwp3cml0ZV9maWxlczoKICAtIGNvbnRlbnQ6IEFsbG93R3JvdXBzIHN2Yy1pa2UKICAgIHBhdGg6IC9ldGMvc3NoL3NzaGRfY29uZmlnCiAgICBhcHBlbmQ6IHRydWUK
            name: cloudinitdisk
